#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZxingCustomScan.Resource", IsApplication=true)]

namespace ZxingCustomScan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ZxingCustomScan.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ZxingCustomScan.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ZxingCustomScan.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int color_dedede = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int color_white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int dimen18 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int dimen20 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int dimen48 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int dimen75 = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_blue_arrow_left = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_blue_flashlight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_blue_photos = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_blue_qrcode = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_white_arrow_left = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_white_flashlight = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_white_photos = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_white_qrcode = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int selector_ic_back = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int selector_ic_flashlight = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int selector_ic_photos = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int selector_ic_qrcode = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int btn_scan = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int contentFrame = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int include1 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int include2 = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int preview_view = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int qrcode_btn_back = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int qrcode_btn_flashlight = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int qrcode_btn_photo = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int tv_value = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int zxing_qrcode_bottom_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxing_qrcode_capture_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxing_qrcode_titlebar_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int text_center = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int text_center_title = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
